// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Realiza login de usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Logar usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequestParams"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Resposta de login",
                        "schema": {
                            "$ref": "#/definitions/controllers.TokenResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/logout": {
            "get": {
                "description": "Desloga o usuário atual",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Deslogar usuário",
                "responses": {
                    "200": {
                        "description": "Usuário deslogado com sucesso",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/auth/refresh-token": {
            "post": {
                "description": "Retorna um novo token de acesso válido por 1 hora",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Refresca o token de acesso",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token de refresh",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Novo token de acesso",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/register_step1": {
            "post": {
                "description": "Cria um novo usuário sem senha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Registrar usuário (Step 1)",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequestStep1"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário registrado",
                        "schema": {
                            "$ref": "#/definitions/resources.UserResource"
                        }
                    }
                }
            }
        },
        "/api/auth/register_step2": {
            "post": {
                "description": "Define a senha do usuário",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Registrar usuário (Step 2)",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequestStep2"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Senha definida",
                        "schema": {
                            "$ref": "#/definitions/resources.UserResource"
                        }
                    }
                }
            }
        },
        "/api/auth/send-validation-code": {
            "post": {
                "description": "Envia código de validação para o e-mail fornecido.",
                "tags": [
                    "Autenticação"
                ],
                "summary": "Envia código de validação",
                "parameters": [
                    {
                        "description": "e-mail",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.ValidationCodeRequestParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Código enviado\" example=\"{\\\"message\\\": \\\"Código enviado com sucesso\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/verify-validation-code": {
            "post": {
                "description": "Verifica se o código de validação é válido.",
                "tags": [
                    "Autenticação"
                ],
                "summary": "Verifica código de validação",
                "parameters": [
                    {
                        "description": "E-mail do usuário",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "email, code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.VerifyCodeRequestParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Código validado com sucesso",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/api/users": {
            "get": {
                "description": "Obtém uma lista de usuários cadastrados",
                "tags": [
                    "Users"
                ],
                "summary": "Listar usuários",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            }
        },
        "/api/users/{id}": {
            "get": {
                "description": "Obtém informações de um usuário em específico",
                "tags": [
                    "Users"
                ],
                "summary": "Listar usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza informações de um usuário em específico",
                "tags": [
                    "Users"
                ],
                "summary": "Atualizar usuário",
                "parameters": [
                    {
                        "description": "Dados do usuário",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/User.UserUpdateDetailsRequestParams"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "User.UserUpdateDetailsRequestParams": {
            "type": "object",
            "required": [
                "birth_date",
                "name",
                "phone"
            ],
            "properties": {
                "birth_date": {
                    "type": "string",
                    "example": "10/01/2000"
                },
                "name": {
                    "type": "string",
                    "example": "João Souza"
                },
                "phone": {
                    "type": "string",
                    "example": "71991112222"
                }
            }
        },
        "auth.LoginRequestParams": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "senha123"
                }
            }
        },
        "auth.RegisterRequestStep1": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                },
                "name": {
                    "type": "string",
                    "minLength": 3,
                    "example": "João Silva"
                }
            }
        },
        "auth.RegisterRequestStep2": {
            "type": "object",
            "required": [
                "confirm_password",
                "hash",
                "password"
            ],
            "properties": {
                "confirm_password": {
                    "type": "string",
                    "example": "senha123"
                },
                "hash": {
                    "type": "string",
                    "example": "72fd3951e5bd758b7619ddc62af1f052"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "senha123"
                }
            }
        },
        "auth.ValidationCodeRequestParams": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                }
            }
        },
        "auth.VerifyCodeRequestParams": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "joao@example.com"
                }
            }
        },
        "controllers.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "resources.UserResource": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
