definitions:
  models.User:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  requests.RegisterRequest:
    properties:
      email:
        type: string
      name:
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  resources.UserResource:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/register:
    post:
      consumes:
      - application/json
      description: Cria um novo usuário
      parameters:
      - description: Dados do usuário
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Usuário registrado
          schema:
            $ref: '#/definitions/resources.UserResource'
      summary: Registrar usuário
      tags:
      - Auth
  /api/users:
    get:
      description: Obtém uma lista de usuários cadastrados
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Listar usuários
      tags:
      - Users
swagger: "2.0"
